// src/components/Calendar.vue
<script setup lang="ts">
import type { EventInput, CalendarOptions } from "@fullcalendar/core";
import FullCalendar from "@fullcalendar/vue3";
import dayGridPlugin from "@fullcalendar/daygrid";
import { ref } from "vue";

const { chosenDate, events } = defineProps<{
	events: EventInput[];
	chosenDate?: Date;
}>();
const MONDAY = 1;

const showSpacer = ref(true);
const calendarOptions = ref({
	now: chosenDate ? chosenDate : new Date(),
	firstDay: MONDAY,
	locale: "pl",
	plugins: [dayGridPlugin],
	initialView: "dayGridMonth",
	events,
	loading: v => (showSpacer.value = v),
	validRange: { start: "2023-02-01" },
	buttonText: { today: chosenDate ? "Wybrana data" : "Dzisiaj" },
} satisfies CalendarOptions);
</script>
<template>
	<span class="my-4 block">
		Kliknij na zdarzenie w kalendarzu aby przejść do TIL na dany dzień
	</span>
	<div v-if="showSpacer" class="h-[610px] w-[750px] bg-skin-fill"></div>
	<FullCalendar :options="calendarOptions"></FullCalendar>
</template>

// src/components/Calendar.tsx
import type { EventInput } from "@fullcalendar/core";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import { useState } from "react";

type CalendarProps = {
  events: EventInput[];
  chosenDate?: Date;
};

const MONDAY = 1;

export const Calendar = ({ events, chosenDate }: CalendarProps) => {
  const [showSpacer, setShowSpacer] = useState(true);
  return (
    <>
      <span className="my-4 block">
        Kliknij na zdarzenie w kalendarzu aby przejść do TIL na dany dzień
      </span>
      {showSpacer && <div className="h-[610px] w-[750px] bg-skin-fill"></div>}
      <FullCalendar
        now={chosenDate ? chosenDate : new Date()}
        firstDay={MONDAY}
        locale="pl"
        plugins={[dayGridPlugin]}
        initialView="dayGridMonth"
        events={events}
        loading={setShowSpacer}
        validRange={{ start: "2023-02-01" }}
        buttonText={{ today: "Dzisiaj" }}
      />
    </>
  );
};
