// src/components/Card.tsx
import Datetime from "./Datetime";
import type { BlogFrontmatter } from "@content/_schemas";
import ReadingTime from "./ReadingTime";

export interface Props {
  href?: string;
  frontmatter: BlogFrontmatter;
  secHeading?: boolean;
  readingTime: number;
}

export default function Card({
  href,
  frontmatter,
  readingTime,
  secHeading = true,
}: Props) {
  const { title, pubDatetime, description } = frontmatter;
  return (
    <li className="my-6">
      <a
        href={href}
        className="inline-block text-lg font-medium text-skin-accent decoration-dashed underline-offset-4 focus-visible:no-underline focus-visible:underline-offset-0"
      >
        {secHeading ? (
          <h2 className="text-lg font-medium decoration-dashed hover:underline">
            {title}
          </h2>
        ) : (
          <h3 className="text-lg font-medium decoration-dashed hover:underline">
            {title}
          </h3>
        )}
      </a>
      <Datetime datetime={pubDatetime} />
      <ReadingTime readingTime={readingTime} size="sm" />
      <p>{description}</p>
    </li>
  );
}

// src/components/Card.vue
<script setup lang="ts">
import Datetime from "./Datetime.vue";
import ReadingTime from "./ReadingTime.vue";

defineProps<{
	href: string;
	frontmatter: {
		title: string;
		pubDatetime: Date;
		description: string;
	};
	secHeading?: boolean;
	readingTime?: number;
}>();
</script>

<template>
	<li class="my-6">
		<a
			:href="href"
			class="inline-block text-lg font-medium text-skin-accent decoration-dashed underline-offset-4 focus-visible:no-underline focus-visible:underline-offset-0"
		>
			<h2 v-if="secHeading" class="text-lg font-medium decoration-dashed hover:underline">
				{{ frontmatter.title }}
			</h2>
			<h3 v-else class="text-lg font-medium decoration-dashed hover:underline">
				{{ frontmatter.title }}
			</h3>
		</a>
		<Datetime :datetime="frontmatter.pubDatetime" />
		<ReadingTime :readingTime="readingTime" size="sm" />
		<p>{{ frontmatter.description }}</p>
	</li>
</template>
